name: aldhakereen
description: "A professional Islamic application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  hijri: ^3.0.0
  google_fonts: ^8.0.2
  adhan: ^2.0.0+1
  adhan_dart: ^1.2.0
  audioplayers: ^6.6.0
  geolocator: ^14.0.2
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.0
  http: ^1.6.0
  path_provider: ^2.1.5
  timezone: ^0.9.2
  sqflite: ^2.4.2+1
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.3
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.6.4
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/content.json
    - assets/images/default_home.png
    - assets/images/default_bg.png
    - assets/images/logo.png
    - assets/audio/adhan.mp3
    - assets/data/quran_db.db

  fonts:
    - family: me_quran
      fonts:
        - asset: assets/font/me_quran.ttf
