name: aldhakereen
description: "A professional Islamic application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  hijri: ^3.0.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/content.json
    - assets/images/default_home.png
    - assets/images/default_bg.png
    - assets/images/logo.png
