/** Design: «واجهة التطبيق الممتدة» — صفحة شفافة ومختصرة تشرح أصل المحتوى ومسار المشروع. */
import { ArrowUpLeft, Database, Github, HeartHandshake } from "lucide-react";
import { OfficialAppFrame } from "@/components/OfficialAppFrame";
import { SiteShell } from "@/components/SiteShell";
import { appAssets } from "@/lib/app-assets";

export default function About() {
  return <SiteShell><main className="about-page section-wrap"><section className="about-hero"><OfficialAppFrame label="SOURCE / 03" compact /><div><p className="section-kicker">عن الذاكرين</p><h1>رفيق يومي،<br />بلغة عربية واضحة.</h1><p>يجمع الذاكرين أدوات اليوم مع مكتبة نصية واسعة. الموقع لا ينشئ محتوى موازيًا؛ بل يفتح المكتبة نفسها التي يعتمدها التطبيق.</p></div></section><section className="about-register"><span><b>01</b> CONTENT.JSON</span><span><b>02</b> 26 مجموعة</span><span><b>03</b> 17,657 مادة</span></section><section className="about-grid"><article><span className="record-number">01 / DATA</span><Database className="h-5 w-5" /><h2>مصدر المحتوى</h2><p>يعتمد الفهرس والنصوص على ملف <span dir="ltr">assets/data/content.json</span> داخل المشروع. تُحمّل النصوص من هذا المصدر عند دخول المكتبة.</p><a href={appAssets.content} target="_blank" rel="noreferrer">فتح الملف الخام <ArrowUpLeft className="h-4 w-4" /></a></article><article><span className="record-number">02 / REPOSITORY</span><Github className="h-5 w-5" /><h2>المشروع مفتوح</h2><p>المستودع يجمع الشفرة وملفات المحتوى وإصدارات Android. يمكن مراجعة التغييرات أو المساهمة من المصدر مباشرة.</p><a href="https://github.com/techtouchAI/Islamic" target="_blank" rel="noreferrer">فتح GitHub <ArrowUpLeft className="h-4 w-4" /></a></article><article><span className="record-number">03 / READING</span><HeartHandshake className="h-5 w-5" /><h2>قراءة أقرب</h2><p>الموقع يعرض محتوى التطبيق للقراءة والاستكشاف؛ أما إعداد الوقت والأذان والذكر التفاعلي فتجدها داخل تطبيق Android.</p></article></section></main></SiteShell>;
}
