/** Design: «محراب رقمي» — رف تنزيلات تحريري واضح؛ لا يدعي توفر رابط مباشر غير موثق. */
import { Archive, Download, FileJson2, Github, LaptopMinimal, ShieldCheck } from "lucide-react";
import { ExternalLink, InfoBadge, PageHero, SiteShell } from "@/components/SiteShell";

const files = [
  { icon: Download, title: "APK للإصدار الموقّع", meta: "Android · Release 1.0.51 · Build 801", copy: "النسخة المناسبة للتثبيت كتحديث عندما تكون موقعة بنفس مفتاح الإصدار المثبت على الجهاز.", href: "https://github.com/techtouchAI/Islamic/releases/tag/v1.0.51-801", cta: "فتح صفحة Release" },
  { icon: Github, title: "الشفرة المصدرية", meta: "GitHub · Flutter / Android", copy: "المستودع العام الذي يضم التطبيق وسير العمل الخاص بالبناء والإصدارات.", href: "https://github.com/techtouchAI/Islamic", cta: "عرض المستودع" },
  { icon: FileJson2, title: "ملف المحتوى المركزي", meta: "assets/data/content.json", copy: "الملف المسؤول عن الأقسام والأدعية والتعقيبات والمحتوى النصي داخل التطبيق.", href: "https://raw.githubusercontent.com/techtouchAI/Islamic/main/assets/data/content.json", cta: "فتح JSON" },
  { icon: Archive, title: "README وملاحظات التطوير", meta: "Documentation · GitHub", copy: "تعليمات التشغيل ومتطلبات المشروع والمرجع الأولي للمساهمة وإدارة المحتوى.", href: "https://github.com/techtouchAI/Islamic/blob/main/README.md", cta: "فتح الدليل" },
];

export default function Downloads() {
  return <SiteShell><PageHero eyebrow="DOWNLOADS / 04" title="ملفات التطبيق في موضع واحد، مع سياق واضح لكل ملف." description="استخدم صفحة الإصدار للـAPK الموقّع، وGitHub للشفرة والوثائق، وملف المحتوى عندما تحتاج إلى تحديث النصوص." />
    <main className="px-5 py-16 sm:py-24 lg:px-10"><div className="mx-auto max-w-[1240px]"><section className="grid overflow-hidden rounded-[30px] border border-[#173a3c]/12 bg-[#fffaf2] lg:grid-cols-[1.05fr_.95fr]"><div className="p-8 lg:p-11"><div className="flex flex-wrap gap-2"><InfoBadge>الإصدار المتاح</InfoBadge><InfoBadge>Android 64-bit</InfoBadge></div><h1 className="mt-5 font-kufi text-3xl font-semibold leading-[1.6] text-[#173a3c]">Release 1.0.51<br />Build 801</h1><p className="mt-4 max-w-xl font-naskh text-xl leading-8 text-[#496869]">يتوفر ملف الإصدار ضمن GitHub Releases. استخدم النسخة الموقعة عندما تريد تثبيت تحديث فوق نسخة Release موجودة.</p><a href="https://github.com/techtouchAI/Islamic/releases/tag/v1.0.51-801" target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#b7833f] px-5 py-3 font-kufi text-xs text-white transition hover:-translate-y-0.5"><Download className="h-4 w-4" /> فتح صفحة التنزيل</a></div><div className="paper-visual min-h-[270px]"><div className="release-seal"><span className="font-plex text-[9px] tracking-[.18em]">SIGNED</span><strong>APK</strong><span className="font-plex text-[9px] tracking-[.18em]">BUILD 801</span></div></div></section>
      <section className="mt-14"><div className="flex flex-col gap-4 border-b border-[#173a3c]/12 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-plex text-[10px] tracking-[0.18em] text-[#b7833f]">FILES / INDEX</p><h2 className="mt-2 font-kufi text-2xl text-[#173a3c]">فهرس الملفات والوجهات</h2></div><p className="font-naskh text-lg text-[#577475]">كل بطاقة تفتح المصدر الأصلي، دون روابط تنزيل مصطنعة.</p></div><div className="divide-y divide-[#173a3c]/12">{files.map(({ icon: Icon, title, meta, copy, href, cta }) => <article key={title} className="grid gap-5 py-7 md:grid-cols-[56px_1fr_auto] md:items-center"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9dfcd] text-[#b7833f]"><Icon className="h-5 w-5" /></div><div><h3 className="font-kufi text-base text-[#173a3c]">{title}</h3><p className="mt-1 font-plex text-[10px] tracking-[0.08em] text-[#b7833f]">{meta}</p><p className="mt-2 max-w-2xl font-naskh text-lg leading-7 text-[#577475]">{copy}</p></div><ExternalLink href={href}>{cta}</ExternalLink></article>)}</div></section>
      <section className="mt-14 rounded-[26px] border border-[#b7833f]/25 bg-[#f0e4cf] p-7 lg:flex lg:items-center lg:justify-between lg:p-9"><div className="flex gap-4"><ShieldCheck className="mt-1 h-6 w-6 shrink-0 text-[#b7833f]" /><div><h2 className="font-kufi text-lg leading-8 text-[#173a3c]">قبل تثبيت APK: افحص التوقيع ورقم الإصدار.</h2><p className="mt-2 font-naskh text-lg leading-7 text-[#496869]">يمكن لتطبيق Android تحديث نسخة سابقة دون حذفها فقط إذا استخدم نفس مفتاح التوقيع وكان رقم build أعلى من النسخة المثبتة.</p></div></div><div className="mt-5 lg:mt-0"><ExternalLink href="/guide">اقرأ خطوات الإعداد</ExternalLink></div></section>
      <div className="mt-8 flex items-center gap-3 font-naskh text-lg text-[#577475]"><LaptopMinimal className="h-5 w-5 text-[#b7833f]" />لا توجد ملفات خفية هنا؛ كل عنصر يرتبط بالمصدر العام الموثق.</div>
    </div></main>
  </SiteShell>;
}
