/** Design: «محراب رقمي» — بطل معماري غير متماثل يضع قيمة التطبيق والتنزيل في الواجهة. */
import { ArrowDownLeft, ArrowUpLeft, BellRing, BookOpen, Clock3, Download, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { heroMihrabSrc } from "@/lib/site-assets";
import { Eyebrow, ExternalLink, InfoBadge, SectionHeading, SiteShell } from "@/components/SiteShell";

const features = [
  { icon: Clock3, label: "وقت الصلاة", copy: "حساب واضح يعتمد الموقع والمصدر المختار." },
  { icon: BookOpen, label: "القرآن والمحتوى", copy: "قراءة وفهرسة ومحتوى منظم في أقسامه." },
  { icon: BellRing, label: "تنبيهات الأذان", copy: "جدولة وتنبيه مسبق واستعادة بعد الإقلاع." },
  { icon: Sparkles, label: "الذكر", copy: "مسبحة تحفظ التقدم وتسبيحة الزهراء 34/33/33." },
];

export default function Home() {
  return <SiteShell>
    <main>
      <section className="relative isolate overflow-hidden bg-[#102e31] px-5 py-14 text-[#f6f1e7] sm:py-20 lg:min-h-[690px] lg:px-10 lg:py-24">
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,46,49,.98)_0%,rgba(16,46,49,.9)_36%,rgba(16,46,49,.28)_100%)]" />
        <img src={heroMihrabSrc} alt="محراب معماري هادئ يعبّر عن هوية تطبيق الذاكرين" className="absolute inset-0 -z-10 h-full w-full object-cover object-[38%_center]" />
        <div className="absolute inset-0 -z-10 opacity-[.13] pattern-grid" />
        <div className="relative mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.05fr_.6fr] lg:items-end">
          <div className="max-w-3xl"><Eyebrow>رفيقك اليومي · إسلامي · عربي</Eyebrow><h1 className="font-kufi text-3xl leading-[1.7] tracking-[-0.065em] sm:text-5xl lg:text-[57px]">وقت الصلاة، واضح<br />في موضعه الصحيح.</h1><p className="mt-6 max-w-xl font-naskh text-xl leading-9 text-[#f6f1e7]/78 sm:text-2xl">الذاكرين يجمع وقت الصلاة، القرآن، الأدعية، الزيارات، الذكر والتخصيص في تجربة واحدة هادئة ومفهومة.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://github.com/techtouchAI/Islamic/releases/tag/v1.0.51-801" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#b7833f] px-5 py-3.5 font-kufi text-xs text-white shadow-[0_12px_30px_rgba(183,131,63,.26)] transition hover:-translate-y-0.5"><Download className="h-4 w-4" /> تنزيل نسخة Android</a><Link href="/features" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-5 py-3.5 font-kufi text-xs text-white transition hover:bg-white/10">اكتشف المزايا <ArrowDownLeft className="h-4 w-4" /></Link></div></div>
          <aside className="mihrab-card bg-[#f6f1e7]/95 p-6 text-[#173a3c] shadow-[0_26px_70px_rgba(0,0,0,.25)] lg:mb-2"><div className="flex items-start justify-between"><div><p className="font-plex text-[10px] tracking-[.18em] text-[#b7833f]">A QUIET DAY</p><h2 className="mt-2 font-kufi text-lg">مسار اليوم</h2></div><InfoBadge>اليوم</InfoBadge></div><div className="mt-6 space-y-4"><div className="flex items-center justify-between border-b border-[#173a3c]/10 pb-4"><span className="font-naskh text-xl">ابدأ بوقت واضح</span><span className="font-plex text-xs text-[#b7833f]">01</span></div><div className="flex items-center justify-between border-b border-[#173a3c]/10 pb-4"><span className="font-naskh text-xl">اقرأ ما تحتاجه</span><span className="font-plex text-xs text-[#b7833f]">02</span></div><div className="flex items-center justify-between"><span className="font-naskh text-xl">أكمل ذكرك</span><span className="font-plex text-xs text-[#b7833f]">03</span></div></div></aside>
        </div>
      </section>

      <section className="relative -mt-8 z-10 px-5 lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-px overflow-hidden rounded-[24px] border border-[#173a3c]/12 bg-[#173a3c]/12 md:grid-cols-4">{features.map(({ icon: Icon, label, copy }) => <article key={label} className="bg-[#fffaf2] p-6 transition hover:bg-[#f0e4cf]"><Icon className="h-5 w-5 text-[#b7833f]" /><h2 className="mt-5 font-kufi text-sm text-[#173a3c]">{label}</h2><p className="mt-2 font-naskh text-lg leading-7 text-[#577475]">{copy}</p></article>)}</div></section>

      <section className="px-5 py-20 sm:py-28 lg:px-10"><div className="mx-auto grid max-w-[1240px] gap-10 lg:grid-cols-[.86fr_1.14fr] lg:items-start"><div className="sticky top-28"><Eyebrow>المزايا الأساسية</Eyebrow><SectionHeading title="ليس تطبيقًا لميزة واحدة." copy="يتحرك الذاكرين مع يومك: من اختيار الموقع إلى تنبيه الصلاة، ومن القراءة إلى الذكر." /><Link href="/features" className="mt-7 inline-flex items-center gap-2 font-kufi text-xs text-[#b7833f] hover:text-[#9d6a2f]">عرض كل المزايا <ArrowUpLeft className="h-4 w-4" /></Link></div><div className="divide-y divide-[#173a3c]/12 border-y border-[#173a3c]/12">{[["أوقات الصلاة", "نتيجة موحدة للعرض والجدولة، مع تمييز GPS والمدينة والـcache والإعداد اليدوي."],["الأذان والإشعارات", "تنبيه مسبق، صوت موحد، استعادة بعد boot، ومسار واضح لصلاحيات Android."],["الأدعية والمحتوى", "مكتبة قابلة للتوسع من ملف JSON مركزي، مصنفة وفق الأقسام والأيام والمناسبات."],["تسبيحة الزهراء", "مرحلات حقيقية 34/33/33، انتقال واضح واهتزاز وحفظ لمسار الذكر."]].map(([title, copy], index) => <article key={title} className="group grid grid-cols-[45px_1fr] gap-4 py-7"><span className="font-plex text-xs text-[#b7833f]">0{index + 1}</span><div><h3 className="font-kufi text-lg text-[#173a3c] group-hover:text-[#b7833f]">{title}</h3><p className="mt-3 font-naskh text-xl leading-8 text-[#496869]">{copy}</p></div></article>)}</div></div></section>

      <section className="bg-[#e9dfcd] px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1240px] gap-9 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="arch-visual h-[350px] shadow-[0_20px_50px_rgba(23,58,60,.16)]"><div className="relative z-10 max-w-[230px] rounded-2xl border border-[#d7b97f]/30 bg-[#f6f1e7]/95 p-5"><p className="font-plex text-[9px] tracking-[.2em] text-[#b7833f]">CONTENT INDEX</p><p className="mt-4 font-kufi text-lg leading-8 text-[#173a3c]">فهرسٌ ينمو مع كل نص جديد.</p><div className="copper-rule mt-5" /></div></div><div><Eyebrow>المحتوى قابل للإدارة</Eyebrow><h2 className="font-kufi text-2xl font-semibold leading-[1.7] text-[#173a3c]">مكتبة التطبيق تتوسع من ملف واحد منظم.</h2><p className="mt-4 font-naskh text-xl leading-8 text-[#496869]">استكشف الأقسام، وأضف الأدعية أو أعمال الأيام وفق بنية واضحة في <code dir="ltr" className="font-plex text-sm text-[#8b5b25]">assets/data/content.json</code>.</p><div className="mt-6"><ExternalLink href="/content">افتح دليل إدارة المحتوى</ExternalLink></div></div></div></section>

      <section className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1240px] overflow-hidden rounded-[30px] bg-[#173a3c] text-[#f6f1e7] lg:grid-cols-[.92fr_1.08fr]"><div className="p-8 lg:p-12"><Eyebrow>DOWNLOAD / ANDROID</Eyebrow><h2 className="font-kufi text-2xl font-semibold leading-[1.7]">حمّل النسخة الموقعة، أو راجع ملفات المشروع.</h2><p className="mt-4 font-naskh text-xl leading-8 text-[#f6f1e7]/72">صفحة الملفات تجمع APK والإصدار والشفرة والمحتوى والوثائق، وتوضح ما يحتاجه كل مسار.</p><Link href="/downloads" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#b7833f] px-5 py-3 font-kufi text-xs text-white transition hover:-translate-y-0.5">التنزيلات والملفات <ArrowUpLeft className="h-4 w-4" /></Link></div><div className="paper-visual min-h-[300px]"><div className="release-seal"><span className="font-plex text-[9px] tracking-[.18em]">ANDROID</span><strong>801</strong><span className="font-plex text-[9px] tracking-[.18em]">RELEASE</span></div></div></div></section>
    </main>
  </SiteShell>;
}
