/// Canonical 67-node dataset for the Prophets and Imams tree.
///
/// Used whenever the active database still carries the legacy three-article
/// entries (for example from an older cached file or a pre-merge cloud sync)
/// so the full tree and all category filters always work out of the box.
const List<Map<String, Object>> kDefaultProphetsTreeNodes = [
  {
    'id': 'adam',
    'title': 'آدم',
    'type': 'prophet',
    'badge': 'نبي',
    'group': 'trunk',
    'desc': 'أبو البشر وأول الأنبياء في الاعتقاد الإسلامي.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'shith',
    'title': 'شيث',
    'type': 'prophet',
    'badge': 'نبي',
    'group': 'trunk',
    'desc': 'من أبناء آدم، وتذكر كتب التراث أنه كان نبيًا.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'anush',
    'title': 'أنوش',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'qinan',
    'title': 'قينان',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'mahalael',
    'title': 'مهلائيل',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'yard',
    'title': 'يارد',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'idris',
    'title': 'إدريس',
    'type': 'prophet',
    'badge': 'نبي',
    'group': 'trunk',
    'desc': 'نبي ذُكر في القرآن، ووصفه الله بالصديقية والنبوة.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'matushalakh',
    'title': 'متوشلخ',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'lamak',
    'title': 'لامك',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'nuh',
    'title': 'نوح',
    'type': 'messenger',
    'badge': 'رسول — أولو العزم',
    'group': 'trunk',
    'desc': 'رسول من أولي العزم، دعا قومه إلى توحيد الله.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'sam',
    'title': 'سام',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'desc': 'أحد أبناء نوح، وتُنسب إليه سلاسل أنساب سامية.',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'arphaxad',
    'title': 'أرفخشذ',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'salakh',
    'title': 'شالخ',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'abir',
    'title': 'عابر',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'faligh',
    'title': 'فالغ',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'raghu',
    'title': 'رعو',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'saruj',
    'title': 'سروج',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'nahur',
    'title': 'ناحور',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'tarah',
    'title': 'تارح',
    'type': 'ancestor',
    'badge': 'الخط الأبوي',
    'group': 'trunk',
    'tags': <String>['ancestors'],
  },
  {
    'id': 'ibrahim',
    'title': 'إبراهيم',
    'type': 'messenger',
    'badge': 'خليل الله — أولو العزم',
    'group': 'trunk',
    'desc': 'خليل الله وأحد أولي العزم، ومن ذريته تفرعت سلالات نبوية كثيرة.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'ismail',
    'title': 'إسماعيل',
    'type': 'messenger',
    'badge': 'نبي ورسول',
    'group': 'trunk',
    'desc': 'ابن إبراهيم، ونبي ورسول.',
    'tags': <String>['prophets'],
  },
  {
    'id': 'adnan_gap',
    'title': 'سلسلة عدنان (بين إسماعيل وعدنان اختلاف)',
    'type': 'gap',
    'badge': '',
    'group': 'trunk',
    'tags': <String>[],
  },
  {
    'id': 'quraish_0',
    'title': 'عدنان',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_1',
    'title': 'معد',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_2',
    'title': 'نزار',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_3',
    'title': 'مضر',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_4',
    'title': 'إلياس',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_5',
    'title': 'مدركة',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_6',
    'title': 'خزيمة',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_7',
    'title': 'كنانة',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_8',
    'title': 'النضر',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_9',
    'title': 'فهر (قريش)',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_10',
    'title': 'غالب',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_11',
    'title': 'لؤي',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_12',
    'title': 'كعب',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_13',
    'title': 'مرة',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_14',
    'title': 'كلاب',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_15',
    'title': 'قصي',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_16',
    'title': 'عبد مناف',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'quraish_17',
    'title': 'هاشم',
    'type': 'quraish',
    'badge': 'نسب قريش',
    'group': 'trunk',
    'tags': <String>['quraish'],
  },
  {
    'id': 'abdulmuttalib',
    'title': 'عبد المطلب',
    'type': 'ancestor',
    'badge': 'الجد',
    'group': 'trunk',
    'strong': true,
    'tags': <String>['ancestors'],
  },
  {
    'id': 'abdullah',
    'title': 'عبد الله',
    'type': 'ancestor',
    'badge': 'والد النبي',
    'group': 'branch_a',
    'strong': true,
    'tags': <String>['ancestors'],
  },
  {
    'id': 'muhammad',
    'title': 'محمد ﷺ',
    'type': 'prophet',
    'badge': 'خاتم الأنبياء',
    'group': 'branch_a',
    'desc': 'ابن عبد الله.',
    'strong': true,
    'tags': <String>['prophets', 'ahl_albayt'],
  },
  {
    'id': 'fatima',
    'title': 'فاطمة الزهراء عليها السلام',
    'type': 'lady',
    'badge': 'الابنة',
    'group': 'branch_a',
    'desc': 'ابنة النبي.',
    'strong': true,
    'tags': <String>['ahl_albayt'],
  },
  {
    'id': 'abotalib',
    'title': 'أبو طالب',
    'type': 'ancestor',
    'badge': 'والد الإمام',
    'group': 'branch_b',
    'strong': true,
    'tags': <String>['ancestors'],
  },
  {
    'id': 'ali',
    'title': 'علي بن أبي طالب عليه السلام',
    'type': 'imam',
    'badge': 'الإمام الأول',
    'group': 'branch_b',
    'desc':
        'ابن أبي طالب وعبد المطلب، أول الأئمة عند الإمامية، وزوج فاطمة الزهراء.',
    'strong': true,
    'tags': <String>['imams', 'ahl_albayt'],
  },
  {
    'id': 'marriage',
    'title': 'تزوج علي من فاطمة بنت النبي',
    'type': 'marriage',
    'badge': '',
    'group': 'marriage',
    'tags': <String>[],
  },
  {
    'id': 'hasan',
    'title': 'الحسن بن علي',
    'type': 'imam',
    'badge': 'الإمام الثاني',
    'group': 'grid',
    'desc': 'ابن علي وفاطمة، الإمام الثاني، عُرف بالحلم والمصالحة وحقن الدماء.',
    'tags': <String>['imams', 'ahl_albayt'],
  },
  {
    'id': 'husayn',
    'title': 'الحسين بن علي',
    'type': 'husayn',
    'badge': 'الإمام الثالث',
    'group': 'grid',
    'desc': 'ابن علي وفاطمة، الإمام الثالث، استشهد في واقعة الطف سنة 61هـ.',
    'tags': <String>['imams', 'ahl_albayt'],
  },
  {
    'id': 'ali_zaynalabidin',
    'title': 'علي بن الحسين زين العابدين',
    'type': 'imam',
    'badge': 'الإمام الرابع',
    'group': 'chain',
    'desc': 'ابن الحسين، الإمام الرابع، عُرف بالعبادة والدعاء.',
    'step': 4,
    'tags': <String>['imams'],
  },
  {
    'id': 'muhammad_albaqir',
    'title': 'محمد الباقر',
    'type': 'imam',
    'badge': 'الإمام الخامس',
    'group': 'chain',
    'desc': 'ابن علي زين العابدين، الإمام الخامس، اشتهر بالعلم والرواية.',
    'step': 5,
    'tags': <String>['imams'],
  },
  {
    'id': 'jafar_alsadiq',
    'title': 'جعفر الصادق',
    'type': 'imam',
    'badge': 'الإمام السادس',
    'group': 'chain',
    'desc':
        'ابن محمد الباقر، الإمام السادس، ارتبط اسمه بمدرسة علمية واسعة في الفقه والحديث.',
    'step': 6,
    'tags': <String>['imams'],
  },
  {
    'id': 'musa_al_kadhim',
    'title': 'موسى الكاظم',
    'type': 'imam',
    'badge': 'الإمام السابع',
    'group': 'chain',
    'desc': 'ابن جعفر الصادق، الإمام السابع، عُرف بكظم الغيظ والصبر.',
    'step': 7,
    'tags': <String>['imams'],
  },
  {
    'id': 'ali_alrida',
    'title': 'علي الرضا',
    'type': 'imam',
    'badge': 'الإمام الثامن',
    'group': 'chain',
    'desc': 'ابن موسى الكاظم، الإمام الثامن، عُرف بالعلم والمناظرات.',
    'step': 8,
    'tags': <String>['imams'],
  },
  {
    'id': 'muhammad_aljawad',
    'title': 'محمد الجواد',
    'type': 'imam',
    'badge': 'الإمام التاسع',
    'group': 'chain',
    'desc':
        'ابن علي الرضا، الإمام التاسع، عُرف بالجود والعلم رغم صغر سنه عند توليه الإمامة.',
    'step': 9,
    'tags': <String>['imams'],
  },
  {
    'id': 'ali_alhadi',
    'title': 'علي الهادي',
    'type': 'imam',
    'badge': 'الإمام العاشر',
    'group': 'chain',
    'desc': 'ابن محمد الجواد، الإمام العاشر، عُرف بالهداية والعبادة.',
    'step': 10,
    'tags': <String>['imams'],
  },
  {
    'id': 'hasan_alaskari',
    'title': 'الحسن العسكري',
    'type': 'imam',
    'badge': 'الإمام الحادي عشر',
    'group': 'chain',
    'desc':
        'ابن علي الهادي، الإمام الحادي عشر، عاش في سامراء وتولى الإمامة بعد أبيه.',
    'step': 11,
    'tags': <String>['imams'],
  },
  {
    'id': 'muhammad_almahdi',
    'title': 'محمد بن الحسن المهدي',
    'type': 'mahdi',
    'badge': 'الإمام الثاني عشر',
    'group': 'chain',
    'desc':
        'ابن الحسن العسكري وفق الاعتقاد الإمامي الاثني عشري، وهو الإمام الثاني عشر، ويُعتقد بغيبته وظهوره في آخر الزمان.',
    'step': 12,
    'tags': <String>['imams'],
  },
  {
    'id': 'supplement_0',
    'title': 'نوح',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'من السابقين قبل إبراهيم.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_1',
    'title': 'السلسلة الإبراهيمية',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'إبراهيم ← إسحاق ← يعقوب.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_2',
    'title': 'أنبياء من الذرية',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc':
        'ومن ذرية إبراهيم/الأنبياء المذكورين في هذا السياق: داود، سليمان، أيوب، يوسف، موسى، هارون، زكريا، يحيى، عيسى، إلياس، اليسع، يونس، إسماعيل، ولوط.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_3',
    'title': 'يوسف',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'يعقوب ← يوسف: نبي من ذرية يعقوب، وقصته مفصلة في سورة يوسف.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_4',
    'title': 'سليمان',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'داود ← سليمان: سليمان ابن داود ونبي وملك.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_5',
    'title': 'يحيى',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'زكريا ← يحيى: يحيى ابن زكريا ونبي.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_6',
    'title': 'عيسى بن مريم',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'نبي وُلد من مريم عليها السلام بمعجزة، وليس له أب بشري.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_7',
    'title': 'موسى وهارون',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc': 'موسى وأخوه هارون: من ذرية بني إسرائيل، وهارون أخو موسى ونبي.',
    'tags': <String>[],
  },
  {
    'id': 'supplement_8',
    'title': 'لوط',
    'type': 'supplement',
    'badge': '',
    'group': 'supplement',
    'desc':
        'من قوم إبراهيم وأهل زمانه، وتذكر كتب التفسير والأنساب صلته بإبراهيم، لكن ليس من الدقة جعله ابنًا لإبراهيم.',
    'tags': <String>[],
  },
];
