name: Build Android APK

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AlDhakereen-Debug-APK
        path: build/app/outputs/flutter-apk/app-debug.apk
